name: jovial_misc
description: Miscellaneous Dart libraries, including interoperability with java.io.DataInputStream and java.io.DataOutputStream.
version: 0.8.4
homepage: https://bill.jovial.com/

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
    pointycastle: ^3.1.0
    async: ^2.5.0
    collection: ^1.14.11
    convert: ^3.0.0
    meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.6
  intl: ^0.18.0

repository: https://github.com/zathras/misc/tree/master/dart/jovial_misc

issues: https://github.com/zathras/misc/issues
